DROP TABLE IF EXISTS SYS_OTHER_INFO;

CREATE TABLE `SYS_OTHER_INFO` (
  `GUID` varchar(38)  NOT NULL DEFAULT '00000' COMMENT '[基本欄] 唯一值',
  `INSERT_USER` varchar(50)  NOT NULL DEFAULT 'SYSTEM' COMMENT '[基本欄] 新增者',
  `INSERT_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '[基本欄] 新增時間',
  `UPDATE_USER` varchar(50)  DEFAULT NULL COMMENT '[基本欄] 更新者',
  `UPDATE_TIME` varchar(50)  DEFAULT NULL COMMENT '[基本欄] 更新時間',
  `ENABLE` tinyint DEFAULT '1' COMMENT '[基本欄] 資料有效性',
  `INFO_SOURCE_TYPE` tinyint DEFAULT '1'  DEFAULT NULL COMMENT '訊息來源類型(1:字典檔文字\2:JS function名稱)',
  `TITLE` varchar(50)  DEFAULT NULL COMMENT '標題(INFO_SOURCE_TYPE為1時對應DocKey文字;2時call對應JS function名稱)',
  `CONTENT` varchar(50)  DEFAULT NULL COMMENT '內文',
  `REMARK` TEXT  DEFAULT NULL COMMENT '備註',
  UNIQUE KEY `GUID_UNIQUE` (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE utf8mb4_unicode_ci 
COMMENT='右側頁籤其他資訊設定';