DROP TABLE IF EXISTS SYS_GROUP;

CREATE TABLE `SYS_GROUP` (
  `GUID` varchar(38)  NOT NULL DEFAULT 'XXXXX' COMMENT '[基本欄] 唯一值',
  `INSERT_USER` varchar(50)  NOT NULL DEFAULT 'SYSTEM' COMMENT '[基本欄] 新增者',
  `INSERT_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '[基本欄] 新增時間',
  `UPDATE_USER` varchar(50)  DEFAULT NULL COMMENT '[基本欄] 更新者',
  `UPDATE_TIME` varchar(50)  DEFAULT NULL COMMENT '[基本欄] 更新時間',
  `ENABLE` tinyint DEFAULT '1' COMMENT '[基本欄] 資料有效性',
  `ID` varchar(50)  DEFAULT NULL COMMENT '群組ID',
  `NAME` varchar(50)  DEFAULT NULL COMMENT '群組名稱',
  `REMARK` TEXT  DEFAULT NULL COMMENT '描述',
  UNIQUE KEY `GUID_UNIQUE` (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE utf8mb4_unicode_ci 
COMMENT='系統權限群組定義';