DROP TABLE IF EXISTS LOG_LOGIN;
DROP TABLE IF EXISTS LOG_LOGIN_HIST;

CREATE TABLE `LOG_LOGIN` (
  `GUID` varchar(38)  NOT NULL DEFAULT 'uuid()' COMMENT '[基本欄] 唯一值',
  `INSERT_USER` varchar(50)  NOT NULL DEFAULT 'SYSTEM' COMMENT '[基本欄] 新增者',
  `INSERT_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '[基本欄] 新增時間',
  `USER_GUID` varchar(38)  DEFAULT NULL COMMENT '登入者GUID',
  `CLIENT_IP` varchar(50)  DEFAULT NULL COMMENT '客戶端IP',
  `ACTION` varchar(50)  DEFAULT NULL COMMENT '動作',
  UNIQUE KEY `GUID_UNIQUE` (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE utf8mb4_unicode_ci 
COMMENT='登入及時紀錄';

CREATE TABLE `LOG_LOGIN_HIST` (
  `GUID` varchar(38)  NOT NULL DEFAULT 'uuid()' COMMENT '[基本欄] 唯一值',
  `INSERT_USER` varchar(50)  NOT NULL DEFAULT 'SYSTEM' COMMENT '[基本欄] 新增者',
  `INSERT_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '[基本欄] 新增時間',
  `USER_GUID` varchar(38)  DEFAULT NULL COMMENT '登入者GUID',
  `CLIENT_IP` varchar(50)  DEFAULT NULL COMMENT '客戶端IP',
  `ACTION` varchar(50)  DEFAULT NULL COMMENT '動作',
  UNIQUE KEY `GUID_UNIQUE` (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE utf8mb4_unicode_ci 
COMMENT='登入歷史紀錄';