DROP TABLE IF EXISTS HR_EMPLOYEE_DEPARTMENT;

CREATE TABLE `HR_EMPLOYEE_DEPARTMENT` (
  `GUID` varchar(38)  NOT NULL DEFAULT 'XXXXX' COMMENT '[基本欄] 唯一值',
  `INSERT_USER` varchar(50)  NOT NULL DEFAULT 'SYSTEM' COMMENT '[基本欄] 新增者',
  `INSERT_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '[基本欄] 新增時間',
  `UPDATE_USER` varchar(50)  DEFAULT NULL COMMENT '[基本欄] 更新者',
  `UPDATE_TIME` varchar(50)  DEFAULT NULL COMMENT '[基本欄] 更新時間',
  `ENABLE` tinyint DEFAULT '1' COMMENT '[基本欄] 資料有效性',
  `EMPLOYEE_GUID` varchar(38)  DEFAULT NULL COMMENT '員工唯一值',
  `DEPARTMENT_GUID` varchar(38)  DEFAULT NULL COMMENT '部門唯一值',
  UNIQUE KEY `GUID_UNIQUE` (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE utf8mb4_unicode_ci 
COMMENT='員工/部門關聯';