DROP TABLE IF EXISTS SYS_PARAM;

CREATE TABLE `SYS_PARAM` (
  `GUID` varchar(38)  NOT NULL DEFAULT '00000' COMMENT '[基本欄] 唯一值',
  `INSERT_USER` varchar(50)  NOT NULL DEFAULT 'SYSTEM' COMMENT '[基本欄] 新增者',
  `INSERT_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '[基本欄] 新增時間',
  `UPDATE_USER` varchar(50)  DEFAULT NULL COMMENT '[基本欄] 更新者',
  `UPDATE_TIME` varchar(50)  DEFAULT NULL COMMENT '[基本欄] 更新時間',
  `ENABLE` tinyint DEFAULT '1' COMMENT '[基本欄] 資料有效性',
  `FUNCTION` varchar(50)  DEFAULT NULL COMMENT '功能代碼',
  `FILTER_KEY` varchar(50)  DEFAULT NULL COMMENT '篩選條件',
  `TEXT` varchar(50)  DEFAULT NULL COMMENT '顯示值',
  `VALUE` varchar(50)  DEFAULT NULL COMMENT '儲存值',
  `TYPE` varchar(50)  DEFAULT NULL COMMENT '參數類型',
  `REMARK` TEXT  DEFAULT NULL COMMENT '備註',
  UNIQUE KEY `GUID_UNIQUE` (`GUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 
COMMENT='系統參數設定';